# -*- coding: utf-8 -*-
"""Toy_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c3Ma2aN9gTWsrFFXjUX6065LgIxsvWXp
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("/content/insurance.csv")

df.head()

df['occupation'].unique()

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

df1 = df.copy()

df1["bmi"] = df1["weight"]/(df1["height"]**2)

def age_group(age):
  if age < 25:
    return "young"
  elif age < 45:
    return "adult"
  elif age<60:
    return "middle_age"
  return "senior"

df1["age_group"] = df1["age"].apply(age_group)

df1.head()

def lifestyle_risk(row):
  if row["bmi"]>30 & row["smoker"]:
    return "high"
  elif row["bmi"]>27 or row["smoker"]:
    return "medium"

  return "low"

df1["lifestyle_risk"] = df1.apply(lifestyle_risk,axis=1)

df1.head()

df1["city"].unique()

tier1 = ['Delhi','Mumbai','Bangalore','Hyderabad','Kolkata',]
tier2 = ['Jaipur', 'Chennai', 'Indore', 'Kota',
        'Chandigarh', 'Pune',  'Lucknow', 'Gaya',
       'Jalandhar', 'Mysore']

def tier(city):
  if city in tier1:
    return 1
  elif city in tier2:
    return 2
  return 3

df1["tier"] = df1["city"].apply(tier)

df1.head()

df1 = df1.drop(columns=["weight","height","city","age","smoker",])[["income_lpa","occupation", "bmi", "age_group", "lifestyle_risk", "tier", "insurance_premium_category"]]

df1.head()

x = df1.iloc[:, :-1]
y = df1.iloc[:, -1]

x

y

categorical_features = ['occupation', 'age_group', 'lifestyle_risk']
numerical_features = ['income_lpa', 'bmi', 'tier']

preprocesor = ColumnTransformer(
    transformers=[
        ("numerical_transformer", StandardScaler(), numerical_features),
        ("categorical_transformer", OneHotEncoder(), categorical_features)
    ]
)

pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocesor),
        ("model", RandomForestClassifier(random_state=42))
    ]
)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

pipeline.fit(x_train,y_train)

import pickle

pickle_model_path = "model.pkl"
with open(pickle_model_path, 'wb') as file:
    pickle.dump(pipeline, file)

